config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      logger.debug "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: created new article #{ "-" * 10}"
      flash[:success] = "Article was succesfully added"
      redirect_to article_path(@article)
    else
      logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: article failed to create... #{ @article.errors.full_messages } #{ "-" * 10}"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      logger.debug "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: updated article #{@article.id} #{ "-" * 10}"
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: failed to update article #{@article.id}...#{ @article.errors.full_messages } #{ "-" * 10}"
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      logger.debug "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: deleted article #{@article.id} #{ "-" * 10}"
      flash[:danger] = "Article was successfully deleted"
      request_redirect(articles_path)
    else
      logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: failed to delete article #{@article.id}...#{ @article.errors.full_messages } #{ "-" * 10}"
      request_redirect(articles_path)
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
      rescue => e
        logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: failed to find article #{params[:id]}...#{ e.message } #{ "-" * 10}"
        flash[:danger] = "Failed to find article"
        request_redirect(articles_path)
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
         flash[:danger] = "You are unauthorized to perform that action."
         request_redirect(root_path)
      end
    end

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-description">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %> </p>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?)%>
          <div class="article-actions">
            <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-xs btn-danger", data: {confirm: "Are you Sure?" } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title , class: "form-control", placeholder: "Article Title", autofocus: true%> <br/>
        </div>
      </div>
      <br>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description" %>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name  do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lrg" %>
        </div>
      </div>
    <% end %>

    <div class=" col-sm-offset-2">
      <%= link_to "Back to All Articles", articles_path %>
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Existing Article</h1>

<%= render partial: 'form' %>
<div class="col-sm-offset-2">
  <%= link_to "Back to Article", article_path(@article) %> </p>
</div>

app/views/articles/index.html.erb
<h1 align="center"> ARTICLES </h1>

<div align="center">
  <%= will_paginate %> 
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %> 
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>
          <%= link_to gravitar_for(@article.user,  size: 75), user_path(@article.user) %>
        </li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li>
          <small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %> </small>
        </li>
      </div>
    </div>
  </ul>
  <h4 align="center" class="description">Description:</h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %> </p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-xs btn-danger", data: {confirm: "Are you Sure?" } %>
    <% end %>
    <%= link_to "All Articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>