config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: { minimum: 3, maximum: 25 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, except: [:index, :new, :create]

  def index
    @categories = Category.paginate(page: params["page"], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      logger.debug "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: created new category #{ "-" * 10}"
      flash[:success] = "Category was succesfully added"
      redirect_to categories_path
    else
      logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: category failed to create... #{ @category.errors.full_messages } #{ "-" * 10}"
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    if @category.update(category_params)
      logger.debug "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: updated category #{ "-" * 10}"
      flash[:success] = "Category: #{@category.name} successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "only admins can perform that action"
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
    rescue => e
      logger.warn "#{ "-" * 10} session: #{session.id}, class: #{self}, method: #{__method__}, message: failed to find category #{params[:id]}...#{ e.message } #{ "-" * 10}"
      flash[:danger] = "Failed to find category"
      request_redirect(categories_path)
  end

end

app/views/categories/_category.html.erb
<span class="badge"> <%=link_to category.name, category_path(category) %> &nbsp; </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name , class: "form-control", placeholder: "Category name", autofocus: true%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lrg" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>

<%= render partial: 'form' %>

<div class="col-sm-offset-2">
  <%= link_to "Back to Category", category_path(@category) %> </p>
</div>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
  <%= will_paginate %>
</div>
<div align="center">
  <% @categories.each do |category| %>
    <ul class='listing'>
      <div class='row'>
        <div class='well col-md-4 col-md-offset-4'>
          <li class='article-title'>
            <%= link_to "#{category.name.capitalize}", category_path(category) %>
          </li>
          <li>
            <small><%= pluralize(category.articles.count, "article" )%> </small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
</div>
<div align="center">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Create New Category</h1>
<%= render 'shared/errors', obj: @category %>
<%= render partial: 'form' %>


<div class=" col-sm-offset-2">
  <%= link_to "Cancel", root_path %>
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category " + @category.name %></h1>

<div align="center">
  <% if logged_in? && current_user.admin? %>
    <div class="row">
      <span class="badge"> <%= link_to "Edit Category", edit_category_path(@category)%></span>
    </div>
  <% end %>

  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>